GUI/menu/server/29
LucasTesnier/ZAAAAAAAAAAAAppy pull request #121
Opened 2022-06-19 08:14 UTC by osvegn

It implements a server menu at the left of the screen. This is a basic menu, without information inside for the moment. There is only interaction and scale adaptation with others menu.

2022-06-19 08:49 UTC, LucasTesnier requested changes
Please do an abastract class

2022-06-19 08:49 UTC, LucasTesnier commented on src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
> +            void _updateBody();
Missing documentation

2022-06-19 09:50 UTC, GuyomT approved these changes
Just add documentation where Lucas said otherwise LGTM

2022-06-20 05:21 UTC, osvegn commented on src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
> +            void _updateBody();
ups, I missed it

2022-06-20 05:21 UTC, osvegn commented
> Please do an abastract class

an abstract for ?

2022-06-20 07:08 UTC, LucasTesnier approved these changes
NTR!

2022-06-20 07:38 UTC, GuyomT approved these changes
LGTM

2022-06-20 07:39 UTC, merged