GUI/map/entities
LucasTesnier/ZAAAAAAAAAAAAppy pull request #146
Opened 2022-06-21 10:09 UTC by GuyomT

Adding the parsing of the response of the server and display

2022-06-21 11:34 UTC, osvegn commented on src/zappy_gui_src/Core/SFML/Map/Map.hpp
> +            void _displayEggs(Tile &tile, sf::CircleShape &eggRpresentation);
missing documentation

2022-06-21 11:57 UTC, osvegn approved these changes
Loooooook goooooood toooooo meeeeee

2022-06-21 12:58 UTC, pariciadra reviewed
Split is the keywork of the review

2022-06-21 12:58 UTC, pariciadra requested changes
Split is the keywork of the review

2022-06-22 05:29 UTC, LucasTesnier approved these changes
NTR!

2022-06-22 05:29 UTC, merged