GUI/menus/add scroll/172
LucasTesnier/ZAAAAAAAAAAAAppy pull request #178
Opened 2022-06-24 07:42 UTC by osvegn

Implement scroll in the bottom menu for players and eggs.

2022-06-24 08:02 UTC, LucasTesnier requested changes
Some missing documentation, otherwise good job

2022-06-24 08:02 UTC, LucasTesnier commented on src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
> +            void scroll(const float &scrollValue);
Missing documentation

2022-06-24 08:02 UTC, LucasTesnier commented on src/zappy_gui_src/Core/SFML/WrapperSFML/Event.hpp
> +        inline void setMouseScrollValue(float value) {
Missing doc

2022-06-24 08:02 UTC, LucasTesnier commented on src/zappy_gui_src/Core/SFML/WrapperSFML/Event.hpp
> +        inline const float &getMouseScrollValue() const {
Missing doc

2022-06-24 13:24 UTC, LucasTesnier approved these changes
NTR!

2022-06-25 07:24 UTC, pariciadra reviewed
LGTM maybe except the 200 char of compute, nevermind

2022-06-25 07:43 UTC, merged