GUI/Core/Parse Status/185
LucasTesnier/ZAAAAAAAAAAAAppy pull request #187
Opened 2022-06-24 17:04 UTC by GuyomT

parsing the status response from the server and sending it to the map

2022-06-24 19:51 UTC, LucasTesnier approved these changes
NTR!

2022-06-25 05:34 UTC, osvegn requested changes
Update the doc and it will be ok

2022-06-25 05:34 UTC, osvegn commented on src/zappy_gui_src/Core/Entity/Entity.hpp
> +        /// \return a string containing the name of the team
invalid doc

2022-06-25 07:21 UTC, pariciadra approved these changes
Lgtm

2022-06-25 08:50 UTC, osvegn approved these changes

2022-06-25 08:54 UTC, merged