GUI/info game/21
LucasTesnier/ZAAAAAAAAAAAAppy pull request #47
Opened 2022-06-01 13:36 UTC by GuyomT

#33 in data_game.h
implementation of a main and a class InfoGame and GUI

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    ORIENTATIONUNDEFINED = 0,
Same

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    GAMESTATUSUNDEFINED = 0,
Same

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    char *name;
Need to add documentation for the struct member.

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    char *team;
Same

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    int life;
Same

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    int x;
Same

2022-06-01 15:53 UTC, LucasTesnier commented on src/zappy_gui/data_game.h
> +    tile_t *tiles;
Same

2022-06-01 15:54 UTC, LucasTesnier commented on src/zappy_gui/main.cpp
> +    } catch (std::exception const &e) {
Create a custom error class will be very usefull for logging informations for the next step of the project. Think about it

2022-06-02 01:00 UTC, pariciadra requested changes
Fix this tiny things pls

2022-06-03 06:40 UTC, osvegn commented on src/zappy_gui/GUI.hpp
> +#define GUI_HPP_
But not in cpp ;)

2022-06-03 17:46 UTC, osvegn requested changes
Some documentation is missing, please add it.
Don't forget to resolve conversation when you resolve a problem ;)

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/GUI.cpp
> +
The \file must be the path of the file:
src/zappy_gui/GUI.cpp

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/GUI.hpp
> +/// \file GUI class
\file must be the path of the file

Use a \brief if you want to describe the file

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/GUI.hpp
> +    void initWindow(std::string const &name = "ZappyGUI");
Need documentation for all parameters

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/GUI.hpp
> +    void initWindow(std::string const &name = "ZappyGUI");
\param

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/GUI.hpp
> +   protected:
useless

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/GameInfo.hpp
> +/// \file Game Info class
\file must be the path of the file

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/data_game.h
> +    LEVELUNDEFINED = 0,
\brief all enum

2022-06-03 17:46 UTC, osvegn commented on src/zappy_gui/data_game.h
> +    ORIENTATIONUNDEFINED = 0,
\brief all enum

2022-06-07 12:20 UTC, LucasTesnier approved these changes
NTR!

2022-06-08 10:02 UTC, pariciadra requested changes
Fix few things pls

2022-06-08 14:25 UTC, osvegn requested changes
Need some changes. Please resolve conflicts

2022-06-09 08:04 UTC, GuyomT commented
Already have been implemented in another branch

2022-06-09 08:04 UTC, closed without merging