Architecure/implement data structures
LucasTesnier/ZAAAAAAAAAAAAppy pull request #84
Opened 2022-06-13 19:24 UTC by Cavonstavant

- Implements object wrapper
- Link structs  together 
- Add some tests

Closes #56

2022-06-13 19:30 UTC, LucasTesnier commented on src/zappy_server_src/core/map.c
> +
Missing /file

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/entity/egg.c
> +/// \file src/zappy_server/core/include/entity/egg.h
The file isn't `egg.h`

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/entity/entity_delete.c
> +/// \file src/zappy_server/core/include/entity/entity_delete.h
The file isn't `entity_delete.h`

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/entity/entity_wrapper.c
> +/// \file src/zappy_server/core/include/entity/entity_wrapper.c
The file isn't in the include directory

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/entity/entity_wrapper_add.c
> +/// \file src/zappy_server/core/include/entity/entity_wrapper_add.c
The file isn't in the include folder

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/include/entity/player.h
> +void delete_player(void *player);
missing `\param` documentation

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/include/entity/player.h
> +player_t *create_player(const char *team_name);
missing `\param` documentation

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/include/map.h
> +
missing `\file`

2022-06-14 08:34 UTC, osvegn commented on src/zappy_server_src/core/server_init.c
> +/// \todo set the players to a random position
is it done or not ?

2022-06-14 12:43 UTC, Cavonstavant commented on src/zappy_server_src/core/server_init.c
> +/// \todo set the players to a random position
not yet, it will be inside a future PR

2022-06-14 14:32 UTC, LucasTesnier approved these changes
NTR! (Just doc but nevermind)

2022-06-14 14:32 UTC, LucasTesnier commented on src/zappy_server_src/core/include/team.h
> +    char *name;
Missing documentation ;)

2022-06-14 14:39 UTC, Cavonstavant commented on src/zappy_server_src/core/include/team.h
> +    char *name;
yes will do

2022-06-14 15:22 UTC, osvegn requested changes
Some minor changes to be, otherwise all is good ;)

2022-06-14 15:22 UTC, osvegn commented on src/zappy_gui_src/Core/SFML/Map/Tile.cpp
> +        return;
Useless change in this pull request, it's fix in another

2022-06-14 15:22 UTC, osvegn commented on src/zappy_server_src/core/auth_command.c
> +    /// return print_retcode(301, NULL, player->player_peer, false);
Do not write comments in code. Or specify it will be added after.

2022-06-14 15:22 UTC, osvegn commented on src/zappy_server_src/core/cmake_error.c
> +}
Useless ?

2022-06-14 15:22 UTC, osvegn commented on src/zappy_server_src/core/include/team.h
> +
missing `\file`

2022-06-14 15:22 UTC, osvegn commented on src/zappy_server_src/core/server_data.c
> +    /// DELETE ALL ENTITIES
Comment in function is not allowed in C.

2022-06-14 15:22 UTC, osvegn commented on src/zappy_server_src/core/team.c
> +
missing `\file`

2022-06-14 15:22 UTC, osvegn commented on src/zappy_server_src/core/teams_remove.c
> +
missing `\file`

2022-06-14 15:30 UTC, 31Nathan requested changes

2022-06-14 15:30 UTC, 31Nathan commented on src/zappy_server_src/core/entity/egg.c
> +    free(egg_data);
When you free a pointer, change its value to NULL

2022-06-14 15:30 UTC, 31Nathan commented on src/zappy_server_src/core/entity/entity.c
> +#include <stdlib.h>
Useless I Think

2022-06-14 15:30 UTC, 31Nathan commented on src/zappy_server_src/core/entity/player.c
> +    free(player_data);
Same, when you free, ptr == NULL

2022-06-14 15:30 UTC, 31Nathan commented on src/zappy_server_src/core/entity/tile.c
> +    free(tile_data);
Free != NULL

2022-06-14 15:30 UTC, 31Nathan commented on src/zappy_server_src/core/server_init.c
> +    /// Init the teams
Comment In Function

2022-06-14 15:48 UTC, Cavonstavant commented on src/zappy_server_src/core/cmake_error.c
> +}
cc @LucasTsr

2022-06-15 22:29 UTC, closed without merging